[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"

  [dev.environment]
    VITE_SUPABASE_URL = "https://ktsnwuyxiiptloedjhtj.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0c253dXl4aWlwdGxvZWRqaHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDkyNjMsImV4cCI6MjA3MzcyNTI2M30.V2iv18JX9_ViU1UnMqiTBdxbaKM4GpkdOf5lBfYypKw"